// bcp-web/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { forkJoin, of } from 'rxjs';
import { catchError, finalize } from 'rxjs/operators';
import {
  ApiService,
  DashboardMetrics,
  DualVerifyHealth,
  DualVerifySessionSummary,
} from '../../services/api.service';
import { environment } from '../../../environments/environment';
import { complianceKeyFromBreakdownName } from '../../../lib/dual-verify-workflow';
import type { ComplianceStatusFilter } from '../../../lib/dual-verify-workflow';
import {
  buildReportStats,
  type ReportStats,
} from '../../../lib/ai-lab/parse-compliance-results';
import {
  parsedResultsFromReport,
  progressPointToReportItem,
} from '../../../lib/dual-verify-report';
import type { DualVerifyAgreement } from '../../../lib/landing-ai/dual-verify-merge';

function normalizeDashboardMetrics(raw: DashboardMetrics & Record<string, unknown>): DashboardMetrics {
  const legacyBreakdown = Array.isArray(raw['riskBreakdown'])
    ? (raw['riskBreakdown'] as { name: string; value: number; color: string }[])
        .filter((r) => /compliant|partial|non/i.test(r.name))
    : [];
  return {
    compliant: Number(raw.compliant ?? raw['compliantItems'] ?? 0),
    partial: Number(raw.partial ?? 0),
    nonCompliant: Number(raw.nonCompliant ?? 0),
    totalFindings: Number(raw.totalFindings ?? 0),
    lastAnalysisDate: String(raw.lastAnalysisDate ?? ''),
    complianceBreakdown:
      raw.complianceBreakdown?.length
        ? raw.complianceBreakdown
        : legacyBreakdown.map((r) => ({
            name: r.name,
            value: r.value,
            color: r.color,
          })),
    recentAnalyses: (raw.recentAnalyses ?? []).map((a) => {
      const row = a as Record<string, unknown>;
      return {
        id: String(row['id'] ?? ''),
        title: String(row['title'] ?? ''),
        date: String(row['date'] ?? ''),
        findings: Number(row['findings'] ?? 0),
        compliant: Number(row['compliant'] ?? 0),
        partial: Number(row['partial'] ?? 0),
        nonCompliant: Number(row['nonCompliant'] ?? 0),
      };
    }),
  };
}

type RecentRow = {
  id: string;
  title: string;
  date: string;
  findings: number;
  compliant: number;
  partial: number;
  nonCompliant: number;
  kind: 'kafka' | 'sync' | 'demo';
  status?: string;
  queryParams: Record<string, string>;
};

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class DashboardComponent implements OnInit {
  readonly apiUrl = environment.apiUrl;

  seed: DashboardMetrics | null = null;
  health: DualVerifyHealth | null = null;
  sessions: DualVerifySessionSummary[] = [];
  sessionStats: ReportStats | null = null;

  healthLoading = true;
  metricsLoading = true;
  sessionsLoading = true;
  statsLoading = false;

  healthError: string | null = null;
  metricsError: string | null = null;
  sessionsError: string | null = null;

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    this.loadHealth();
    this.loadMetrics();
    this.loadSessions();
  }

  private loadHealth(): void {
    this.healthLoading = true;
    this.healthError = null;
    this.api
      .getDualVerifyHealth()
      .pipe(finalize(() => (this.healthLoading = false)))
      .subscribe({
        next: (r) => {
          this.health = r.data;
        },
        error: () => {
          this.healthError =
            `Cannot reach BCP API at ${environment.apiUrl}. ` +
            'If the API is up, republish bcp-api with CORS for this web URL.';
        },
      });
  }

  private loadMetrics(): void {
    this.metricsLoading = true;
    this.metricsError = null;
    this.api
      .getDashboard()
      .pipe(finalize(() => (this.metricsLoading = false)))
      .subscribe({
        next: (r) => {
          this.seed = normalizeDashboardMetrics(
            r.data as DashboardMetrics & Record<string, unknown>,
          );
        },
        error: () => {
          this.metricsError = 'Metrics unavailable';
          this.seed = null;
        },
      });
  }

  private loadSessions(): void {
    this.sessionsLoading = true;
    this.sessionsError = null;
    forkJoin({
      kafka: this.api.listDualVerifySessions().pipe(catchError(() => of({ data: [] }))),
      kafkaNest: this.api.listNestDualVerifySessions().pipe(catchError(() => of({ data: [] }))),
      compliance: this.api
        .listComplianceSessions('dual-leaf', 10)
        .pipe(catchError(() => of({ sessions: [] }))),
    })
      .pipe(finalize(() => (this.sessionsLoading = false)))
      .subscribe({
        next: ({ kafka, kafkaNest, compliance }) => {
          const merged: DualVerifySessionSummary[] = [
            ...(kafkaNest.data ?? []),
            ...(kafka.data ?? []),
          ];
          const seen = new Set(merged.map((s) => s.id));
          for (const c of compliance.sessions ?? []) {
            if (c.source === 'compare_cache' || seen.has(c.id)) continue;
            seen.add(c.id);
            merged.push({
              id: c.id,
              status: 'saved',
              granularity: c.granularity ?? 'dual-leaf',
              totalPoints: c.comparedPoints,
              completedPoints: c.comparedPoints,
              failedPoints: 0,
              phase2Model: 'saved',
              transport: 'db',
              updatedAt: c.updatedAt ?? c.label,
              label: c.label,
            });
          }
          this.sessions = merged;
          this.loadLatestSessionStats();
        },
        error: () => {
          this.sessionsError = 'Sessions unavailable';
          this.sessions = [];
        },
      });
  }

  get compliantCount(): number {
    return this.sessionStats?.compliant ?? this.seed?.compliant ?? 0;
  }

  get partialCount(): number {
    return this.sessionStats?.partial ?? this.seed?.partial ?? 0;
  }

  get nonCompliantCount(): number {
    return this.sessionStats?.nonCompliant ?? this.seed?.nonCompliant ?? 0;
  }

  get totalFindings(): number {
    const fromStats = this.sessionStats?.total ?? 0;
    const fromSeed = this.seed?.totalFindings ?? 0;
    const sum = this.compliantCount + this.partialCount + this.nonCompliantCount;
    return Math.max(fromStats, fromSeed, sum);
  }

  get metricsLoadingAny(): boolean {
    return this.metricsLoading || this.statsLoading;
  }

  get hasComplianceMetrics(): boolean {
    if (this.metricsLoadingAny) return true;
    return this.totalFindings > 0;
  }

  get complianceBreakdown(): { name: string; value: number; color: string }[] {
    if (this.sessionStats) {
      const rows: { name: string; value: number; color: string }[] = [];
      if (this.sessionStats.compliant > 0) {
        rows.push({ name: 'Compliant', value: this.sessionStats.compliant, color: '#22c55e' });
      }
      if (this.sessionStats.partial > 0) {
        rows.push({ name: 'Partial', value: this.sessionStats.partial, color: '#eab308' });
      }
      if (this.sessionStats.nonCompliant > 0) {
        rows.push({ name: 'Non-compliant', value: this.sessionStats.nonCompliant, color: '#ef4444' });
      }
      if (rows.length) return rows;
    }
    return (this.seed?.complianceBreakdown ?? []).filter((r) => r.value > 0);
  }

  get showBreakdownSection(): boolean {
    return this.metricsLoadingAny || this.complianceBreakdown.length > 0;
  }

  get lastAnalysisLabel(): string {
    if (this.metricsLoading) return 'Loading…';
    return this.seed?.lastAnalysisDate || '—';
  }

  private loadLatestSessionStats(): void {
    const latest = this.sessions.find(
      (s) => s.completedPoints > 0 && s.transport !== 'db' && s.status === 'completed',
    );
    if (!latest) return;

    this.statsLoading = true;
    this.api
      .getJob(latest.id)
      .pipe(finalize(() => (this.statsLoading = false)))
      .subscribe({
        next: (r) => {
          const items = (r.data?.points ?? [])
            .filter((p) => p.status === 'completed' && p.landingMessage && p.llmMessage)
            .map((p) =>
              progressPointToReportItem({
                pointId: p.pointId,
                pointTitle: p.pointTitle,
                status: p.status,
                landingMessage: p.landingMessage,
                llmMessage: p.llmMessage,
                agreementJson: p.agreementJson as DualVerifyAgreement | undefined,
                errorMessage: p.errorMessage,
              }),
            );
          if (!items.length) return;
          this.sessionStats = buildReportStats(parsedResultsFromReport(items, 'llm'));
        },
        error: () => {
          /* dashboard still works from API metrics */
        },
      });
  }

  get persistenceMode(): string {
    return this.health?.persistence?.mode ?? 'memory';
  }

  get completedPoints(): number {
    return this.sessions.reduce((n, s) => n + s.completedPoints, 0);
  }

  get activeJobs(): number {
    return this.sessions.filter((s) =>
      ['running', 'queued', 'processing'].includes(s.status),
    ).length;
  }

  get firstActiveSession(): DualVerifySessionSummary | undefined {
    return this.sessions.find((s) =>
      ['running', 'queued', 'processing'].includes(s.status),
    );
  }

  get latestSession(): DualVerifySessionSummary | undefined {
    return this.sessions[0];
  }

  get recentRows(): RecentRow[] {
    const rows: RecentRow[] = this.sessions
      .slice(0, 8)
      .map((s) => ({
        id: s.id,
        title: `Dual verify · ${s.granularity}`,
        date: (s.updatedAt ?? '').slice(0, 16).replace('T', ' '),
        findings: s.completedPoints,
        compliant: 0,
        partial: 0,
        nonCompliant: s.failedPoints,
        kind: 'kafka' as const,
        status: s.status,
        queryParams: this.sessionRecordQuery(s),
      }))
      .filter((r) => r.findings > 0 || r.nonCompliant > 0);

    for (const a of this.seed?.recentAnalyses ?? []) {
      const isDemo = a.id.includes('demo');
      if (a.compliant + a.partial + a.nonCompliant === 0 && a.findings === 0) continue;
      rows.push({
        id: a.id,
        title: a.title,
        date: a.date,
        findings: a.findings,
        compliant: a.compliant,
        partial: a.partial,
        nonCompliant: a.nonCompliant,
        kind: isDemo ? 'demo' : 'sync',
        queryParams: { saved: `compliance:${a.id}` },
      });
    }
    return rows;
  }

  complianceKey(name: string): ComplianceStatusFilter | null {
    return complianceKeyFromBreakdownName(name);
  }

  analysisQuery(compliance?: ComplianceStatusFilter): Record<string, string> {
    const q = this.latestSession ? this.sessionRecordQuery(this.latestSession) : {};
    if (compliance) return { ...q, compliance };
    return q;
  }

  sessionRecordQuery(s: DualVerifySessionSummary): Record<string, string> {
    if (s.transport === 'db' || s.status === 'saved') {
      return { saved: `compliance:${s.id}` };
    }
    return { session: s.id };
  }

  recordQuery(sessionId?: string | null): Record<string, string> {
    if (sessionId) return { session: sessionId };
    return {};
  }
}

<div class="header">
  <div>
    <p class="eyebrow">BCP App · Bank Compliance Platform</p>
    <h1>Compliance Dashboard</h1>
    <p class="muted">SNB UAE / DIFC · Last analysis: {{ lastAnalysisLabel }}</p>
  </div>
</div>

@if (healthError) {
  <div class="alert error">{{ healthError }}</div>
  <p class="muted">Health check: <code>curl {{ apiUrl }}/dual-verify-kafka/health</code></p>
}

@if (!healthLoading && persistenceMode === 'memory') {
  <div class="alert">
    Persistence is memory-only — not using shared Supabase.
    @if (health?.persistence?.hint) {
      <br /><strong>{{ health!.persistence!.hint }}</strong>
    } @else {
      Set <code>ConnectionStrings:PostgreSQL</code> or <code>Supabase:Db*</code> in
      <code>bcp-api/appsettings.Development.json</code> and restart the API.
    }
  </div>
}

<div class="status-grid">
  <div class="card" [class.is-loading]="healthLoading">
    <span class="label">Transport</span>
    @if (healthLoading) {
      <span class="sk-value" aria-hidden="true"></span>
      <span class="sk-line short" aria-hidden="true"></span>
    } @else {
      <strong class="emerald">{{ health?.transport ?? '—' }}</strong>
      <small>{{ health?.kafkaConfigured ? 'Azure Event Hubs' : 'Local queue' }}</small>
    }
  </div>
  <div class="card" [class.is-loading]="healthLoading">
    <span class="label">Persistence</span>
    @if (healthLoading) {
      <span class="sk-value" aria-hidden="true"></span>
      <span class="sk-line short" aria-hidden="true"></span>
    } @else {
      <strong [class]="persistenceMode === 'memory' ? 'red' : 'emerald'">{{ persistenceMode }}</strong>
      <small>{{ health?.persistence?.fileDataDir }}</small>
    }
  </div>
  <div class="card" [class.is-loading]="sessionsLoading">
    <span class="label">Analyzed points</span>
    @if (sessionsLoading) {
      <span class="sk-value" aria-hidden="true"></span>
      <span class="sk-line short" aria-hidden="true"></span>
    } @else {
      <strong class="violet">{{ completedPoints }}</strong>
      <small>{{ sessions.length }} session(s)</small>
    }
  </div>
  <div class="card" [class.is-loading]="sessionsLoading">
    <span class="label">Active jobs</span>
    @if (sessionsLoading) {
      <span class="sk-value" aria-hidden="true"></span>
      <span class="sk-line short" aria-hidden="true"></span>
    } @else {
      <strong class="amber">{{ activeJobs }}</strong>
      <small>{{ activeJobs > 0 ? 'Pipeline running' : 'Idle' }}</small>
    }
  </div>
</div>

@if (hasComplianceMetrics) {
  <div class="metrics-grid">
    <div class="card metric" [class.is-loading]="metricsLoadingAny">
      <span>Compliant</span>
      @if (metricsLoadingAny) {
        <span class="sk-value" aria-hidden="true"></span>
      } @else if (compliantCount > 0) {
        <a
          class="metric-link"
          [routerLink]="['/dual-verify']"
          [queryParams]="analysisQuery('compliant')"
          title="View compliant analyses"
        >
          <strong class="green">{{ compliantCount }}</strong>
        </a>
      } @else {
        <strong class="muted-num">0</strong>
      }
    </div>
    <div class="card metric" [class.is-loading]="metricsLoadingAny">
      <span>Partial</span>
      @if (metricsLoadingAny) {
        <span class="sk-value" aria-hidden="true"></span>
      } @else if (partialCount > 0) {
        <a
          class="metric-link"
          [routerLink]="['/dual-verify']"
          [queryParams]="analysisQuery('partial')"
          title="View partial analyses"
        >
          <strong class="amber">{{ partialCount }}</strong>
        </a>
      } @else {
        <strong class="muted-num">0</strong>
      }
    </div>
    <div class="card metric" [class.is-loading]="metricsLoadingAny">
      <span>Non-compliant</span>
      @if (metricsLoadingAny) {
        <span class="sk-value" aria-hidden="true"></span>
      } @else if (nonCompliantCount > 0) {
        <a
          class="metric-link"
          [routerLink]="['/dual-verify']"
          [queryParams]="analysisQuery('non-compliant')"
          title="View non-compliant analyses"
        >
          <strong class="red">{{ nonCompliantCount }}</strong>
        </a>
      } @else {
        <strong class="muted-num">0</strong>
      }
    </div>
    <div class="card metric" [class.is-loading]="metricsLoadingAny">
      <span>Total findings</span>
      @if (metricsLoadingAny) {
        <span class="sk-value" aria-hidden="true"></span>
      } @else {
        <strong>{{ totalFindings }}</strong>
      }
    </div>
  </div>
}

<div class="two-col">
  @if (showBreakdownSection) {
    <section class="card" [class.is-loading]="metricsLoadingAny">
      <h2>Compliance breakdown</h2>
      @if (metricsLoadingAny) {
        <ul class="breakdown-list skeleton-list">
          @for (i of [1, 2, 3]; track i) {
            <li><span class="sk-line" aria-hidden="true"></span></li>
          }
        </ul>
      } @else if (complianceBreakdown.length === 0) {
        <p class="muted">No breakdown data yet.</p>
      } @else {
        <ul class="breakdown-list">
          @for (r of complianceBreakdown; track r.name) {
            @if (complianceKey(r.name); as key) {
              <li>
                <a [routerLink]="['/dual-verify']" [queryParams]="analysisQuery(key)">
                  <span class="dot" [style.background]="r.color"></span>
                  <span class="name">{{ r.name }}</span>
                  <strong>{{ r.value }}</strong>
                </a>
              </li>
            } @else {
              <li>
                <span class="dot" [style.background]="r.color"></span>
                <span class="name">{{ r.name }}</span>
                <strong>{{ r.value }}</strong>
              </li>
            }
          }
        </ul>
      }
    </section>
  }

  <section class="card" [class.is-loading]="sessionsLoading" [class.span-full]="!showBreakdownSection">
    <h2>Recent sessions</h2>
    @if (sessionsLoading) {
      <ul class="session-list skeleton-list">
        @for (i of [1, 2, 3]; track i) {
          <li><span class="sk-line" aria-hidden="true"></span></li>
        }
      </ul>
    } @else if (sessionsError) {
      <p class="muted error-inline">{{ sessionsError }}</p>
    } @else if (sessions.length === 0) {
      <p class="muted">No sessions yet. Use Dual Verify in the menu to start.</p>
    } @else {
      <ul class="session-list">
        @for (s of sessions.slice(0, 6); track s.id) {
          <li>
            <a [routerLink]="['/dual-verify']" [queryParams]="sessionRecordQuery(s)">
              <span>{{ s.label }}</span>
              <span class="badge" [class.done]="s.status === 'completed'">{{ s.status }}</span>
            </a>
          </li>
        }
      </ul>
    }
  </section>
</div>

<section class="card" [class.is-loading]="sessionsLoading || metricsLoading">
  <h2>Recent analyses</h2>
  @if (sessionsLoading || metricsLoading) {
    <ul class="recent-list skeleton-list">
      @for (i of [1, 2, 3]; track i) {
        <li><span class="sk-line tall" aria-hidden="true"></span></li>
      }
    </ul>
  } @else if (metricsError && recentRows.length === 0) {
    <p class="muted error-inline">{{ metricsError }}</p>
  } @else if (recentRows.length === 0) {
    <p class="muted">No analysis records yet.</p>
  } @else {
    <ul class="recent-list">
      @for (a of recentRows; track a.kind + a.id) {
        <li>
          <a [routerLink]="['/dual-verify']" [queryParams]="a.queryParams" class="recent-row">
            <span class="kind" [class]="a.kind">{{ a.kind === 'kafka' ? 'KAFKA' : a.kind === 'demo' ? 'DEMO' : 'SYNC' }}</span>
            <div class="recent-body">
              <span class="recent-title">{{ a.title }}</span>
              <span class="recent-meta">
                {{ a.date }} · {{ a.findings }} findings
                @if (a.status) { · {{ a.status }} }
              </span>
            </div>
            <div class="recent-badges">
              @if (a.compliant > 0) {
                <span class="pill ok">{{ a.compliant }} Compliant</span>
              }
              @if (a.partial > 0) {
                <span class="pill warn">{{ a.partial }} Partial</span>
              }
              @if (a.nonCompliant > 0) {
                <span class="pill bad">{{ a.nonCompliant }} Non-compliant</span>
              }
            </div>
          </a>
        </li>
      }
    </ul>
  }
</section>

// apps/bcpweb/src/app/dashboard/page.tsx
'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import {
  Activity,
  CheckCircle2,
  Database,
  Layers,
  Radio,
  Zap,
} from 'lucide-react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { AppShell } from '@/components/layout/AppShell';
import { SeverityBadge } from '@/components/ui/SeverityBadge';
import { getDashboard } from '@/lib/api';
import {
  getDualVerifyHealth,
  listComplianceSessions,
  listDualVerifySessions,
  type DualVerifyHealth,
  type DualVerifySessionSummary,
} from '@/lib/dual-verify-api';
import type { BcpwebDashboardMetrics } from '@/types';

type RecentRow = {
  id: string;
  title: string;
  date: string;
  findings: number;
  critical: number;
  high: number;
  href: string;
  kind: 'kafka' | 'sync' | 'demo';
  status?: string;
};

/** Compliance dashboard — Reguliq MIS + live Kafka pipeline */
export default function DashboardPage() {
  const [seed, setSeed] = useState<BcpwebDashboardMetrics | null>(null);
  const [health, setHealth] = useState<DualVerifyHealth | null>(null);
  const [kafkaSessions, setKafkaSessions] = useState<DualVerifySessionSummary[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const [dash, h, sessions, compliance] = await Promise.all([
          getDashboard(),
          getDualVerifyHealth(),
          listDualVerifySessions(),
          listComplianceSessions('dual-leaf', 10),
        ]);
        if (cancelled) return;
        setSeed(dash);
        setHealth(h);
        const merged = [...sessions];
        for (const c of compliance) {
          if (!merged.some((s) => s.id === c.id)) {
            merged.push({
              id: c.id,
              status: 'saved',
              granularity: c.granularity ?? 'dual-leaf',
              totalPoints: c.comparedPoints,
              completedPoints: c.comparedPoints,
              failedPoints: 0,
              phase2Model: 'saved',
              transport: 'db',
              updatedAt: c.label,
              label: c.label,
            });
          }
        }
        setKafkaSessions(merged);
      } catch (e) {
        console.error(e);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  const pipelineStats = useMemo(() => {
    const completed = kafkaSessions.reduce((n, s) => n + s.completedPoints, 0);
    const failed = kafkaSessions.reduce((n, s) => n + s.failedPoints, 0);
    const active = kafkaSessions.filter(
      (s) => s.status === 'running' || s.status === 'queued',
    ).length;
    return { completed, failed, active, sessionCount: kafkaSessions.length };
  }, [kafkaSessions]);

  const recentRows: RecentRow[] = useMemo(() => {
    const rows: RecentRow[] = kafkaSessions.slice(0, 8).map((s) => ({
      id: s.id,
      title: `Kafka dual verify · ${s.granularity}`,
      date: s.updatedAt.slice(0, 16).replace('T', ' '),
      findings: s.completedPoints,
      critical: s.failedPoints,
      high: 0,
      href: `/dual-verify?session=${encodeURIComponent(s.id)}`,
      kind: 'kafka' as const,
      status: s.status,
    }));
    if (seed) {
      for (const a of seed.recentAnalyses) {
        rows.push({
          id: a.id,
          title: a.title,
          date: a.date,
          findings: a.findings,
          critical: a.critical,
          high: a.high,
          href: `/analyse/report/${a.id}`,
          kind: a.id.includes('demo') ? 'demo' : 'sync',
        });
      }
    }
    return rows;
  }, [kafkaSessions, seed]);

  const persistenceMode = health?.persistence?.mode ?? 'memory';
  const persistenceOk = persistenceMode === 'supabase' || persistenceMode === 'file';

  if (loading || !seed) {
    return (
      <AppShell>
        <p className="text-slate-400">Loading dashboard…</p>
      </AppShell>
    );
  }

  const compliantPct =
    seed.totalFindings > 0
      ? Math.round((seed.compliantItems / seed.totalFindings) * 100)
      : 0;

  return (
    <AppShell>
      <div className="mb-6 flex flex-wrap items-start justify-between gap-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wider text-emerald-400">
            Reguliq Compliance
          </p>
          <h1 className="text-2xl font-bold">Compliance Dashboard</h1>
          <p className="text-sm text-slate-400">
            SNB UAE / DIFC Branch · Last analysis: {seed.lastAnalysisDate}
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          <Link
            href="/dual-verify"
            className="rounded-lg border border-emerald-500/40 bg-emerald-500/10 px-4 py-2 text-sm font-medium text-emerald-300 hover:bg-emerald-500/20"
          >
            Kafka Dual Verify →
          </Link>
          <Link
            href="/analyse"
            className="rounded-lg bg-emerald-500 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-400"
          >
            Sync Analyse →
          </Link>
        </div>
      </div>

      <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <PipelineCard
          icon={<Radio className="h-4 w-4 text-emerald-400" />}
          label="Transport"
          value={health?.transport ?? '—'}
          sub={health?.kafkaConfigured ? 'Azure Event Hubs' : 'Local queue'}
          tone="text-emerald-400"
        />
        <PipelineCard
          icon={<Database className="h-4 w-4 text-sky-400" />}
          label="Persistence"
          value={
            persistenceMode === 'supabase'
              ? 'Supabase'
              : persistenceMode === 'file'
                ? 'Disk'
                : 'None'
          }
          sub={persistenceOk ? 'Results saved' : 'Do not run paid jobs'}
          tone={
            persistenceMode === 'memory'
              ? 'text-red-400'
              : persistenceMode === 'supabase'
                ? 'text-emerald-400'
                : 'text-sky-400'
          }
        />
        <PipelineCard
          icon={<Layers className="h-4 w-4 text-violet-400" />}
          label="Dual verify points"
          value={String(pipelineStats.completed)}
          sub={`${pipelineStats.sessionCount} session(s) · ${pipelineStats.failed} failed`}
          tone="text-violet-300"
        />
        <PipelineCard
          icon={<Activity className="h-4 w-4 text-amber-400" />}
          label="Active jobs"
          value={String(pipelineStats.active)}
          sub={pipelineStats.active > 0 ? 'Pipeline running' : 'Idle'}
          tone="text-amber-300"
        />
      </div>

      {health?.persistence?.hint && !persistenceOk && (
        <div className="mb-6 rounded-xl border border-red-500/40 bg-red-500/10 px-4 py-3 text-sm text-red-200">
          {health.persistence.hint}
        </div>
      )}

      <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <MetricCard label="Critical Gaps" value={seed.criticalGaps} tone="text-red-400" sub="Immediate action required" />
        <MetricCard label="High Risk" value={seed.highRisk} tone="text-orange-400" sub="Significant exposure" />
        <MetricCard label="Total Findings" value={seed.totalFindings} tone="text-white" sub="Demo + live sessions" />
        <MetricCard label="Compliant Items" value={seed.compliantItems} tone="text-blue-400" sub="Fully addressed" />
      </div>

      <div className="mb-6 grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border border-white/10 bg-white/5 p-5">
          <h2 className="mb-4 font-semibold">Risk breakdown</h2>
          <div className="flex items-center gap-6">
            <div className="relative h-40 w-40">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie data={seed.riskBreakdown} dataKey="value" innerRadius={45} outerRadius={70}>
                    {seed.riskBreakdown.map((entry) => (
                      <Cell key={entry.name} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
              <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
                <span className="text-lg font-semibold text-slate-300">{compliantPct}%</span>
              </div>
            </div>
            <div className="space-y-2 text-sm">
              {seed.riskBreakdown.map((r) => (
                <div key={r.name} className="flex items-center gap-2">
                  <span className="h-2 w-2 rounded-full" style={{ background: r.color }} />
                  <span className="text-slate-400">{r.name}</span>
                  <span className="font-medium">{r.value}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-white/10 bg-white/5 p-5">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="font-semibold">Kafka pipeline</h2>
            <Link href="/dual-verify" className="text-sm text-emerald-400 hover:underline">
              Open workbench →
            </Link>
          </div>
          <ul className="space-y-2 text-sm">
            {kafkaSessions.length === 0 ? (
              <li className="rounded-lg border border-dashed border-white/10 p-4 text-slate-500">
                No Kafka sessions yet.{' '}
                <Link href="/dual-verify" className="text-emerald-400 hover:underline">
                  Start dual verify
                </Link>
              </li>
            ) : (
              kafkaSessions.slice(0, 5).map((s) => (
                <li key={s.id}>
                  <Link
                    href={`/dual-verify?session=${encodeURIComponent(s.id)}`}
                    className="flex items-center justify-between rounded-lg border border-white/5 bg-black/20 px-3 py-2 hover:bg-white/5"
                  >
                    <div className="min-w-0">
                      <p className="truncate font-medium">{s.label}</p>
                      <p className="text-xs text-slate-500">
                        {s.phase2Model} · {s.transport}
                      </p>
                    </div>
                    <span
                      className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium uppercase ${
                        s.status === 'completed'
                          ? 'bg-emerald-500/20 text-emerald-400'
                          : s.status === 'failed'
                            ? 'bg-red-500/20 text-red-400'
                            : 'bg-amber-500/20 text-amber-400'
                      }`}
                    >
                      {s.status}
                    </span>
                  </Link>
                </li>
              ))
            )}
          </ul>
          {health && (
            <p className="mt-3 text-xs text-slate-500">
              Topics: {health.topics.jobs} · {health.topics.results}
            </p>
          )}
        </div>
      </div>

      <div className="mb-6 rounded-xl border border-white/10 bg-white/5 p-5">
        <h2 className="mb-4 font-semibold">Remediation tracker</h2>
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-slate-500">
              <th className="pb-2">Item</th>
              <th className="pb-2">Severity</th>
              <th className="pb-2">Target</th>
              <th className="pb-2">Status</th>
            </tr>
          </thead>
          <tbody>
            {seed.remediationItems.map((row) => (
              <tr key={row.item} className="border-t border-white/5">
                <td className="py-2">{row.item}</td>
                <td className="py-2">
                  <SeverityBadge severity={row.severity} />
                </td>
                <td className="py-2 text-slate-400">{row.target}</td>
                <td className="py-2 text-slate-400">{row.status}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="rounded-xl border border-white/10 bg-white/5 p-5">
        <div className="mb-4 flex items-center justify-between">
          <h2 className="font-semibold">Recent analyses</h2>
          <Link href="/dual-verify" className="text-sm text-emerald-400 hover:underline">
            All dual verify →
          </Link>
        </div>
        <div className="space-y-3">
          {recentRows.map((a) => (
            <Link
              key={`${a.kind}-${a.id}`}
              href={a.href}
              className="flex items-center justify-between rounded-lg border border-white/5 bg-black/20 p-3 hover:bg-white/5"
            >
              <div className="flex items-center gap-3">
                <span
                  className={`rounded px-2 py-1 text-xs ${
                    a.kind === 'kafka'
                      ? 'bg-violet-500/20 text-violet-300'
                      : a.kind === 'demo'
                        ? 'bg-red-500/20 text-red-400'
                        : 'bg-sky-500/20 text-sky-300'
                  }`}
                >
                  {a.kind === 'kafka' ? 'KAFKA' : a.kind === 'demo' ? 'DEMO' : 'SYNC'}
                </span>
                <div>
                  <p className="font-medium">{a.title}</p>
                  <p className="text-xs text-slate-500">
                    {a.date} · {a.findings} findings
                    {a.status ? ` · ${a.status}` : ''}
                  </p>
                </div>
              </div>
              <div className="flex gap-2">
                {a.critical > 0 && (
                  <span className="rounded-full bg-red-500/20 px-2 py-0.5 text-xs text-red-400">
                    {a.critical} {a.kind === 'kafka' ? 'Failed' : 'Critical'}
                  </span>
                )}
                {a.high > 0 && (
                  <span className="rounded-full bg-orange-500/20 px-2 py-0.5 text-xs text-orange-400">
                    {a.high} High
                  </span>
                )}
                {a.kind === 'kafka' && a.critical === 0 && (
                  <CheckCircle2 className="h-4 w-4 text-emerald-500" />
                )}
              </div>
            </Link>
          ))}
        </div>
      </div>

      <div className="mt-6 grid gap-4 sm:grid-cols-3">
        <QuickAction
          href="/dual-verify"
          icon={<Zap className="h-5 w-5 text-emerald-400" />}
          title="Kafka Dual Verify"
          desc="Landing AI + Gemini · async · export PDF/Excel"
        />
        <QuickAction
          href="/analyse"
          icon={<Activity className="h-5 w-5 text-sky-400" />}
          title="Sync Analyse"
          desc="Upload regulation + policy · instant Gemini gap report"
        />
        <QuickAction
          href="/reg-library"
          icon={<Layers className="h-5 w-5 text-violet-400" />}
          title="Regulation Library"
          desc="CBUAE TFS guidelines and clause catalogue"
        />
      </div>
    </AppShell>
  );
}

function PipelineCard({
  icon,
  label,
  value,
  sub,
  tone,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  sub: string;
  tone: string;
}) {
  return (
    <div className="rounded-xl border border-white/10 bg-gradient-to-br from-white/5 to-transparent p-4">
      <div className="mb-2 flex items-center gap-2 text-xs uppercase tracking-wide text-slate-500">
        {icon}
        {label}
      </div>
      <p className={`text-2xl font-bold capitalize ${tone}`}>{value}</p>
      <p className="mt-1 text-xs text-slate-500">{sub}</p>
    </div>
  );
}

function MetricCard({
  label,
  value,
  tone,
  sub,
}: {
  label: string;
  value: number;
  tone: string;
  sub: string;
}) {
  return (
    <div className="rounded-xl border border-white/10 bg-white/5 p-5">
      <p className="text-xs uppercase tracking-wide text-slate-500">{label}</p>
      <p className={`mt-1 text-4xl font-bold ${tone}`}>{value}</p>
      <p className="mt-1 text-xs text-slate-500">{sub}</p>
    </div>
  );
}

function QuickAction({
  href,
  icon,
  title,
  desc,
}: {
  href: string;
  icon: React.ReactNode;
  title: string;
  desc: string;
}) {
  return (
    <Link
      href={href}
      className="rounded-xl border border-white/10 bg-white/5 p-4 transition hover:border-emerald-500/30 hover:bg-emerald-500/5"
    >
      <div className="mb-2">{icon}</div>
      <p className="font-medium">{title}</p>
      <p className="mt-1 text-xs text-slate-500">{desc}</p>
    </Link>
  );
}
